import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

import {
    FaMobileAlt,
    FaUser,
    FaCalendarAlt,
    FaVenusMars,
    FaLock
} from "react-icons/fa";

import {
    checkSinger,
    sendOTP,
    verifyOTP,
    registerSinger
} from "../services/singerService";

import "./SingerLogin.css";


// ==========================================================
// BEATS INFINITY - SINGER REGISTRATION
// ==========================================================
//
// NEW SINGER FLOW
//
// Mobile
//    ↓
// Check Mobile
//    ↓
// Send OTP
//    ↓
// Verify OTP
//    ↓
// Create 4 Digit PIN
//    ↓
// Singer Details
//    ↓
// Continue to Song Selection
//    ↓
// Fresh Singer Song Selection
//
// IMPORTANT
//
// 1. OTP is generated by the BACKEND.
// 2. Frontend does NOT generate OTP.
// 3. Registration data is stored temporarily.
// 4. A NEW registration session is created every time.
// 5. Previous singer song-selection data is explicitly cleared.
// 6. Singer is identified later by the registered singer ID.
// ==========================================================


const SingerRegistration = () => {

    const navigate = useNavigate();


    // ======================================================
    // SCREEN
    // ======================================================

    const [screen, setScreen] =
        useState("mobile");

    /*
        mobile
        otp
        pin
        details
    */


    // ======================================================
    // FORM STATE
    // ======================================================

    const [mobile, setMobile] =
        useState("");

    const [otp, setOtp] =
        useState("");

    const [pin, setPin] =
        useState("");

    const [confirmPin, setConfirmPin] =
        useState("");

    const [name, setName] =
        useState("");

    const [dateOfBirth, setDateOfBirth] =
        useState("");

    const [gender, setGender] =
        useState("");


    // ======================================================
    // OTP STATE
    // ======================================================

    const [generatedOtp, setGeneratedOtp] =
        useState("");

    const [otpExpiresAt, setOtpExpiresAt] =
        useState(null);


    // ======================================================
    // UI STATE
    // ======================================================

    const [loading, setLoading] =
        useState(false);

    const [error, setError] =
        useState("");

    const [success, setSuccess] =
        useState("");


    // ======================================================
    // HELPERS
    // ======================================================

    const clearMessages = () => {

        setError("");
        setSuccess("");

    };


    const normalizeMobile = (value) => {

        return String(value || "")
            .replace(/\D/g, "")
            .slice(-10);

    };


    const cleanOtp = (value) => {

        return String(value || "")
            .replace(/\D/g, "")
            .slice(0, 6);

    };


    const cleanPin = (value) => {

        return String(value || "")
            .replace(/\D/g, "")
            .slice(0, 4);

    };


    // ======================================================
    // CLEAR OLD SINGER SESSION
    // ======================================================
    //
    // VERY IMPORTANT
    //
    // This prevents a newly registered singer from inheriting
    // another singer's previous song-selection/submission state.
    //
    // We deliberately clear ONLY singer workflow/session keys.
    // ======================================================

    const clearPreviousSingerSession = () => {

        const keysToClear = [

            "beatsInfinitySinger",

            "beatsInfinitySingerId",

            "beatsInfinitySingerSession",

            "beatsInfinityRegistration",

            "beatsInfinityPendingRegistration",

            "beatsInfinitySelectedSongs",

            "beatsInfinitySongSelection",

            "beatsInfinitySubmittedSongs",

            "beatsInfinityPayment",

            "beatsInfinityPaymentStatus",

            "selectedSongs",

            "selectedSongIds",

            "singerId",

            "singer_id"

        ];


        keysToClear.forEach((key) => {

            try {

                sessionStorage.removeItem(key);

            }
            catch (error) {

                console.warn(
                    "Unable to clear sessionStorage key:",
                    key,
                    error
                );

            }


            try {

                localStorage.removeItem(key);

            }
            catch (error) {

                console.warn(
                    "Unable to clear localStorage key:",
                    key,
                    error
                );

            }

        });

    };


    // ======================================================
    // MOBILE CHANGE
    // ======================================================

    const handleMobileChange = (event) => {

        const value =
            normalizeMobile(
                event.target.value
            );

        setMobile(value);

        clearMessages();

    };


    // ======================================================
    // OTP CHANGE
    // ======================================================

    const handleOtpChange = (event) => {

        const value =
            cleanOtp(
                event.target.value
            );

        setOtp(value);

        clearMessages();

    };


    // ======================================================
    // PIN CHANGE
    // ======================================================

    const handlePinChange = (event) => {

        const value =
            cleanPin(
                event.target.value
            );

        setPin(value);

        clearMessages();

    };


    // ======================================================
    // CONFIRM PIN CHANGE
    // ======================================================

    const handleConfirmPinChange = (event) => {

        const value =
            cleanPin(
                event.target.value
            );

        setConfirmPin(value);

        clearMessages();

    };


    // ======================================================
    // NAME CHANGE
    // ======================================================

    const handleNameChange = (event) => {

        setName(
            event.target.value
        );

        clearMessages();

    };


    // ======================================================
    // DOB CHANGE
    // ======================================================

    const handleDateOfBirthChange = (event) => {

        setDateOfBirth(
            event.target.value
        );

        clearMessages();

    };


    // ======================================================
    // GENDER CHANGE
    // ======================================================

    const handleGenderChange = (event) => {

        setGender(
            event.target.value
        );

        clearMessages();

    };


    // ======================================================
    // START REGISTRATION
    // ======================================================

    const handleMobileSubmit = async (event) => {

        event.preventDefault();

        clearMessages();


        if (mobile.length !== 10) {

            setError(
                "Please enter a valid 10 digit mobile number."
            );

            return;

        }


        setLoading(true);

        setGeneratedOtp("");

        setOtpExpiresAt(null);


        try {

            // ------------------------------------------------
            // IMPORTANT
            //
            // Start a completely fresh singer registration.
            // ------------------------------------------------

            clearPreviousSingerSession();


            // ------------------------------------------------
            // Check whether singer already exists
            // ------------------------------------------------

            const singerResult =
                await checkSinger(
                    mobile
                );


            console.log(
                "Singer check result:",
                singerResult
            );


            if (
                singerResult &&
                singerResult.success &&
                singerResult.exists
            ) {

                setError(
                    "This mobile number is already registered. Please login instead."
                );

                return;

            }


            // ------------------------------------------------
            // Send registration OTP
            // ------------------------------------------------

            const otpResult =
                await sendOTP(
                    mobile,
                    "registration"
                );


            console.log(
                "Registration OTP result:",
                otpResult
            );


            if (
                !otpResult ||
                !otpResult.success
            ) {

                setError(
                    otpResult?.message ||
                    "Unable to generate OTP."
                );

                return;

            }


            // ------------------------------------------------
            // Development mode
            //
            // Backend currently returns OTP for testing.
            // ------------------------------------------------

            if (otpResult.otp) {

                setGeneratedOtp(
                    String(
                        otpResult.otp
                    )
                );

            }


            if (
                otpResult.expires_at
            ) {

                setOtpExpiresAt(
                    otpResult.expires_at
                );

            }


            // ------------------------------------------------
            // Save ONLY mobile + registration state.
            //
            // No songs are stored here.
            // ------------------------------------------------

            sessionStorage.setItem(

                "beatsInfinityPendingRegistration",

                JSON.stringify({

                    mobile,

                    otpVerified: false,

                    registrationStarted: true,

                    registrationSession:
                        Date.now()

                })

            );


            setSuccess(
                "OTP generated successfully."
            );


            setScreen(
                "otp"
            );

        }
        catch (error) {

            console.error(
                "Registration OTP error:",
                error
            );


            setError(
                error.message ||
                "Unable to generate OTP. Please try again."
            );

        }
        finally {

            setLoading(false);

        }

    };


    // ======================================================
    // VERIFY REGISTRATION OTP
    // ======================================================

    const handleOtpSubmit = async (event) => {

        event.preventDefault();

        clearMessages();


        if (
            !/^\d{6}$/.test(otp)
        ) {

            setError(
                "Please enter the 6-digit OTP."
            );

            return;

        }


        setLoading(true);


        try {

            const result =
                await verifyOTP(

                    mobile,

                    otp,

                    "registration"

                );


            console.log(
                "OTP verification result:",
                result
            );


            if (
                !result ||
                !result.success ||
                !result.verified
            ) {

                setError(
                    result?.message ||
                    "Invalid or expired OTP."
                );

                setOtp("");

                return;

            }


            // ------------------------------------------------
            // Retrieve pending registration
            // ------------------------------------------------

            let pendingRegistration = {};


            try {

                const stored =
                    sessionStorage.getItem(
                        "beatsInfinityPendingRegistration"
                    );


                if (stored) {

                    pendingRegistration =
                        JSON.parse(stored);

                }

            }
            catch (error) {

                console.warn(
                    "Unable to read pending registration:",
                    error
                );

            }


            // ------------------------------------------------
            // Save verified state
            // ------------------------------------------------

            sessionStorage.setItem(

                "beatsInfinityPendingRegistration",

                JSON.stringify({

                    ...pendingRegistration,

                    mobile,

                    otpVerified: true,

                    registrationSession:
                        pendingRegistration.registrationSession ||
                        Date.now()

                })

            );


            setOtp("");

            setGeneratedOtp("");

            setSuccess(
                "OTP verified successfully."
            );


            setTimeout(() => {

                clearMessages();

                setScreen(
                    "pin"
                );

            }, 400);

        }
        catch (error) {

            console.error(
                "OTP verification error:",
                error
            );


            setError(
                error.message ||
                "Unable to verify OTP."
            );


            setOtp("");

        }
        finally {

            setLoading(false);

        }

    };


    // ======================================================
    // RESEND OTP
    // ======================================================

    const handleResendOtp = async () => {

        clearMessages();

        setOtp("");

        setGeneratedOtp("");

        setOtpExpiresAt(null);

        setLoading(true);


        try {

            const result =
                await sendOTP(

                    mobile,

                    "registration"

                );


            console.log(
                "Resend OTP result:",
                result
            );


            if (
                !result ||
                !result.success
            ) {

                setError(
                    result?.message ||
                    "Unable to resend OTP."
                );

                return;

            }


            if (result.otp) {

                setGeneratedOtp(
                    String(
                        result.otp
                    )
                );

            }


            if (result.expires_at) {

                setOtpExpiresAt(
                    result.expires_at
                );

            }


            setSuccess(
                "A new OTP has been generated."
            );

        }
        catch (error) {

            console.error(
                "Resend OTP error:",
                error
            );


            setError(
                error.message ||
                "Unable to resend OTP."
            );

        }
        finally {

            setLoading(false);

        }

    };


    // ======================================================
    // CREATE PIN
    // ======================================================

    const handlePinSubmit = (event) => {

        event.preventDefault();

        clearMessages();


        if (
            !/^\d{4}$/.test(pin)
        ) {

            setError(
                "PIN must contain exactly 4 digits."
            );

            return;

        }


        if (
            !/^\d{4}$/.test(confirmPin)
        ) {

            setError(
                "Please confirm your 4 digit PIN."
            );

            return;

        }


        if (
            pin !== confirmPin
        ) {

            setError(
                "PIN and Confirm PIN do not match."
            );

            return;

        }


        // ------------------------------------------------
        // Verify OTP registration state
        // ------------------------------------------------

        let pendingRegistration = {};


        try {

            const stored =
                sessionStorage.getItem(
                    "beatsInfinityPendingRegistration"
                );


            if (stored) {

                pendingRegistration =
                    JSON.parse(stored);

            }

        }
        catch {

            pendingRegistration = {};

        }


        if (
            !pendingRegistration.otpVerified
        ) {

            setError(
                "Please verify your OTP before creating a PIN."
            );

            setScreen(
                "otp"
            );

            return;

        }


        // ------------------------------------------------
        // Save PIN temporarily.
        //
        // Singer is NOT created in DB yet.
        // ------------------------------------------------

        sessionStorage.setItem(

            "beatsInfinityPendingRegistration",

            JSON.stringify({

                ...pendingRegistration,

                mobile,

                pin,

                otpVerified: true,

                pinCreated: true

            })

        );


        setPin("");

        setConfirmPin("");


        setScreen(
            "details"
        );

    };


    // ======================================================
    // REGISTER / CONTINUE
    // ======================================================

    const handleDetailsSubmit = async (event) => {

        event.preventDefault();

        clearMessages();


        // ------------------------------------------------
        // Validate name
        // ------------------------------------------------

        if (!name.trim()) {

            setError(
                "Please enter your name."
            );

            return;

        }


        // ------------------------------------------------
        // Validate DOB
        // ------------------------------------------------

        if (!dateOfBirth) {

            setError(
                "Please enter your date of birth."
            );

            return;

        }


        // ------------------------------------------------
        // Validate gender
        // ------------------------------------------------

        if (!gender) {

            setError(
                "Please select your gender."
            );

            return;

        }


        // ------------------------------------------------
        // Retrieve pending registration
        // ------------------------------------------------

        let pendingRegistration = {};


        try {

            const stored =
                sessionStorage.getItem(
                    "beatsInfinityPendingRegistration"
                );


            if (stored) {

                pendingRegistration =
                    JSON.parse(stored);

            }

        }
        catch {

            pendingRegistration = {};

        }


        if (
            !pendingRegistration.otpVerified
        ) {

            setError(
                "Registration verification is incomplete."
            );

            setScreen(
                "otp"
            );

            return;

        }


        if (
            !pendingRegistration.pinCreated ||
            !pendingRegistration.pin
        ) {

            setError(
                "Please create your PIN first."
            );

            setScreen(
                "pin"
            );

            return;

        }


        setLoading(true);


        try {

            // =================================================
            // CREATE THE ACTUAL SINGER IN DATABASE
            // =================================================
            //
            // This is important.
            //
            // We create the singer BEFORE song selection so
            // every song request can be tied to the correct
            // singer UUID.
            // =================================================

            const registrationData = {

                mobile,

                singer_name:
                    name.trim(),

                gender,

                date_of_birth:
                    dateOfBirth,

                pin:
                    pendingRegistration.pin

            };


            console.log(
                "Creating singer:",
                {
                    ...registrationData,
                    pin: "****"
                }
            );


            const result =
                await registerSinger(
                    registrationData
                );


            console.log(
                "Singer registration result:",
                result
            );


            if (
                !result ||
                !result.success
            ) {

                setError(
                    result?.message ||
                    "Unable to create singer profile."
                );

                return;

            }


            // =================================================
            // DETERMINE SINGER ID
            // =================================================

            const singer =
                result.singer ||
                result.data ||
                null;


            const singerId =
                singer?.id ||
                result.singer_id ||
                result.id ||
                null;


            if (!singerId) {

                console.error(
                    "Registration response did not contain singer ID:",
                    result
                );


                setError(
                    "Singer was registered, but the singer ID was not returned. Please contact the administrator."
                );

                return;

            }


            // =================================================
            // IMPORTANT: CREATE A FRESH SINGER SESSION
            // =================================================

            const singerSession = {

                id:
                    singerId,

                singer_id:
                    singerId,

                mobile,

                singer_name:
                    name.trim(),

                gender,

                date_of_birth:
                    dateOfBirth,

                registrationType:
                    "new",

                authenticated:
                    true,

                registrationCompleted:
                    true,

                songSelectionCompleted:
                    false,

                paymentStatus:
                    "not_started",

                sessionCreatedAt:
                    Date.now()

            };


            // ------------------------------------------------
            // Clear any old singer/song data AGAIN
            // ------------------------------------------------

            clearPreviousSingerSession();


            // ------------------------------------------------
            // Save the NEW singer identity
            //
            // IMPORTANT:
            //
            // The singer identity is the CANONICAL session and
            // must live in localStorage - this is what
            // SingerDashboard.jsx, MySongs.jsx, SingerPayment.jsx
            // and LoginForm.jsx all read from. Using
            // sessionStorage here made a freshly registered
            // singer invisible to their own dashboard.
            // ------------------------------------------------

            localStorage.setItem(

                "beatsInfinitySinger",

                JSON.stringify(
                    singerSession
                )

            );


            localStorage.setItem(

                "beatsInfinitySingerId",

                String(
                    singerId
                )

            );


            localStorage.setItem(

                "beatsInfinitySingerSession",

                JSON.stringify(
                    singerSession
                )

            );


            // ------------------------------------------------
            // Registration data
            // ------------------------------------------------

            sessionStorage.setItem(

                "beatsInfinityRegistration",

                JSON.stringify({

                    ...registrationData,

                    singer_id:
                        singerId,

                    registrationCompleted:
                        true

                })

            );


            // =================================================
            // CRITICAL
            //
            // Start the new singer with EMPTY song selection.
            //
            // Do NOT copy any previous singer's selections.
            // =================================================

            sessionStorage.setItem(

                "beatsInfinitySelectedSongs",

                JSON.stringify([])

            );


            sessionStorage.setItem(

                "beatsInfinitySongSelection",

                JSON.stringify({

                    singer_id:
                        singerId,

                    selected_song_ids:
                        [],

                    submitted:
                        false,

                    submitted_at:
                        null

                })

            );


            // ------------------------------------------------
            // Remove temporary registration
            // ------------------------------------------------

            sessionStorage.removeItem(
                "beatsInfinityPendingRegistration"
            );


            // ------------------------------------------------
            // Remove any stale submission state
            // ------------------------------------------------

            sessionStorage.removeItem(
                "beatsInfinitySubmittedSongs"
            );

            sessionStorage.removeItem(
                "beatsInfinityPayment"
            );

            sessionStorage.removeItem(
                "beatsInfinityPaymentStatus"
            );


            console.log(
                "Fresh singer session created:",
                singerSession
            );


            setSuccess(
                "Registration completed successfully."
            );


            // =================================================
            // GO TO SINGER DASHBOARD / SONG SELECTION
            //
            // IMPORTANT:
            //
            // "/singer-song-selection" has no route - song
            // selection already lives inline in MySongs.jsx on
            // the Singer Dashboard, so that is the correct
            // destination after registration.
            // =================================================

            setTimeout(() => {

                navigate(
                    "/singer-dashboard",
                    {
                        replace: true,

                        state: {

                            singerId,

                            singer: singerSession,

                            isNewSinger: true,

                            selectedSongIds: []

                        }

                    }
                );

            }, 500);

        }
        catch (error) {

            console.error(
                "Singer registration error:",
                error
            );


            setError(
                error.message ||
                "Unable to complete registration."
            );

        }
        finally {

            setLoading(false);

        }

    };


    // ======================================================
    // BACK TO LOGIN
    // ======================================================

    const handleBackToLogin = () => {

        clearMessages();

        navigate(
            "/login"
        );

    };


    // ======================================================
    // GO BACK
    // ======================================================

    const handleBack = () => {

        clearMessages();


        if (
            screen === "otp"
        ) {

            setOtp("");

            setGeneratedOtp("");

            setScreen(
                "mobile"
            );

            return;

        }


        if (
            screen === "pin"
        ) {

            setPin("");

            setConfirmPin("");

            setScreen(
                "otp"
            );

            return;

        }


        if (
            screen === "details"
        ) {

            setScreen(
                "pin"
            );

            return;

        }

    };


    // ======================================================
    // RENDER - MOBILE
    // ======================================================

    const renderMobileScreen = () => (

        <form
            onSubmit={
                handleMobileSubmit
            }
        >

            <div className="form-group">

                <label>

                    <FaMobileAlt />

                    Mobile Number

                </label>


                <input
                    type="tel"
                    inputMode="numeric"
                    maxLength="10"
                    value={mobile}
                    onChange={
                        handleMobileChange
                    }
                    placeholder="Enter 10 digit mobile number"
                    autoComplete="tel"
                    disabled={loading}
                />

            </div>


            <button
                type="submit"
                className="login-button"
                disabled={
                    loading ||
                    mobile.length !== 10
                }
            >

                {loading
                    ? "PLEASE WAIT..."
                    : "SEND OTP"
                }

            </button>


            <button
                type="button"
                className="back-button"
                onClick={
                    handleBackToLogin
                }
                disabled={loading}
            >

                ← Back to Login

            </button>

        </form>

    );


    // ======================================================
    // RENDER - OTP
    // ======================================================

    const renderOtpScreen = () => (

        <form
            onSubmit={
                handleOtpSubmit
            }
        >

            <div className="form-group">

                <label>

                    <FaLock />

                    Enter OTP

                </label>


                <input
                    type="tel"
                    inputMode="numeric"
                    maxLength="6"
                    value={otp}
                    onChange={
                        handleOtpChange
                    }
                    placeholder="Enter 6 digit OTP"
                    autoComplete="one-time-code"
                    disabled={loading}
                />

            </div>


            {generatedOtp && (

                <div className="otp-development">

                    <strong>
                        Development OTP
                    </strong>

                    <div className="otp-code">
                        {generatedOtp}
                    </div>

                    <small>
                        This OTP is shown only during local development.
                    </small>

                </div>

            )}


            {otpExpiresAt && (

                <div className="otp-expiry">

                    OTP expires at{" "}
                    {new Date(
                        otpExpiresAt
                    ).toLocaleTimeString()}

                </div>

            )}


            <button
                type="submit"
                className="login-button"
                disabled={
                    loading ||
                    otp.length !== 6
                }
            >

                {loading
                    ? "VERIFYING..."
                    : "VERIFY OTP"
                }

            </button>


            <button
                type="button"
                className="secondary-button"
                onClick={
                    handleResendOtp
                }
                disabled={loading}
            >

                RESEND OTP

            </button>


            <button
                type="button"
                className="back-button"
                onClick={
                    handleBack
                }
                disabled={loading}
            >

                ← Change Mobile Number

            </button>

        </form>

    );


    // ======================================================
    // RENDER - PIN
    // ======================================================

    const renderPinScreen = () => (

        <form
            onSubmit={
                handlePinSubmit
            }
        >

            <div className="form-group">

                <label>

                    <FaLock />

                    Create 4 Digit PIN

                </label>


                <input
                    type="password"
                    inputMode="numeric"
                    maxLength="4"
                    value={pin}
                    onChange={
                        handlePinChange
                    }
                    placeholder="Enter 4 digit PIN"
                    autoComplete="new-password"
                    disabled={loading}
                />

            </div>


            <div className="form-group">

                <label>

                    <FaLock />

                    Confirm PIN

                </label>


                <input
                    type="password"
                    inputMode="numeric"
                    maxLength="4"
                    value={confirmPin}
                    onChange={
                        handleConfirmPinChange
                    }
                    placeholder="Re-enter 4 digit PIN"
                    autoComplete="new-password"
                    disabled={loading}
                />

            </div>


            <button
                type="submit"
                className="login-button"
                disabled={
                    loading ||
                    pin.length !== 4 ||
                    confirmPin.length !== 4
                }
            >

                CONTINUE

            </button>


            <button
                type="button"
                className="back-button"
                onClick={
                    handleBack
                }
                disabled={loading}
            >

                ← Back to OTP

            </button>

        </form>

    );


    // ======================================================
    // RENDER - DETAILS
    // ======================================================

    const renderDetailsScreen = () => (

        <form
            onSubmit={
                handleDetailsSubmit
            }
        >

            <div className="form-group">

                <label>

                    <FaUser />

                    Singer Name

                </label>


                <input
                    type="text"
                    value={name}
                    onChange={
                        handleNameChange
                    }
                    placeholder="Enter your name"
                    autoComplete="name"
                    disabled={loading}
                />

            </div>


            <div className="form-group">

                <label>

                    <FaCalendarAlt />

                    Date of Birth

                </label>


                <input
                    type="date"
                    value={dateOfBirth}
                    onChange={
                        handleDateOfBirthChange
                    }
                    disabled={loading}
                />

            </div>


            <div className="form-group">

                <label>

                    <FaVenusMars />

                    Gender

                </label>


                <select
                    value={gender}
                    onChange={
                        handleGenderChange
                    }
                    disabled={loading}
                >

                    <option value="">
                        Select Gender
                    </option>

                    <option value="Male">
                        Male
                    </option>

                    <option value="Female">
                        Female
                    </option>

                    <option value="Other">
                        Other
                    </option>

                </select>

            </div>


            <div className="registration-summary">

                <div>
                    <strong>Mobile:</strong>{" "}
                    {mobile}
                </div>

                <div>
                    <strong>OTP:</strong>{" "}
                    Verified ✓
                </div>

                <div>
                    <strong>PIN:</strong>{" "}
                    Created ✓
                </div>

            </div>


            <button
                type="submit"
                className="login-button"
                disabled={loading}
            >

                {loading
                    ? "CREATING PROFILE..."
                    : "CONTINUE TO SONG SELECTION"
                }

            </button>


            <button
                type="button"
                className="back-button"
                onClick={
                    handleBack
                }
                disabled={loading}
            >

                ← Back

            </button>

        </form>

    );


    // ======================================================
    // RENDER
    // ======================================================

    return (

        <div className="singer-login-page">

            <div className="singer-login-background">

                <div className="music-note note-one">
                    ♪
                </div>

                <div className="music-note note-two">
                    ♫
                </div>

                <div className="music-note note-three">
                    ♪
                </div>

                <div className="music-note note-four">
                    ♬
                </div>

            </div>


            <div className="singer-login-card">


                {/* ==================================================
                    BRAND
                ================================================== */}

                <div className="brand-top">

                    <div className="brand-infinity">
                        ∞
                    </div>

                    <div>

                        <div className="brand-name">
                            BEATS ∞ INFINITY
                        </div>

                        <div className="brand-tagline">
                            Unleash the Harmony in You
                        </div>

                    </div>

                </div>


                {/* ==================================================
                    TITLE
                ================================================== */}

                <div className="login-title">

                    {screen === "mobile" &&
                        "Join Beats Infinity"
                    }

                    {screen === "otp" &&
                        "Verify Your Mobile"
                    }

                    {screen === "pin" &&
                        "Create Your PIN"
                    }

                    {screen === "details" &&
                        "Your Singer Profile"
                    }

                </div>


                <div className="login-subtitle">

                    {screen === "mobile" &&
                        "Enter your mobile number to get started"
                    }

                    {screen === "otp" &&
                        "Enter the OTP sent to your mobile number"
                    }

                    {screen === "pin" &&
                        "Create a secure 4 digit PIN"
                    }

                    {screen === "details" &&
                        "Complete your profile before selecting songs"
                    }

                </div>


                {/* ==================================================
                    ERROR
                ================================================== */}

                {error && (

                    <div className="message error-message">

                        ❌ {error}

                    </div>

                )}


                {/* ==================================================
                    SUCCESS
                ================================================== */}

                {success && (

                    <div className="message success-message">

                        ✅ {success}

                    </div>

                )}


                {/* ==================================================
                    SCREENS
                ================================================== */}

                {screen === "mobile" &&
                    renderMobileScreen()
                }

                {screen === "otp" &&
                    renderOtpScreen()
                }

                {screen === "pin" &&
                    renderPinScreen()
                }

                {screen === "details" &&
                    renderDetailsScreen()
                }


                {/* ==================================================
                    FOOTER
                ================================================== */}

                <div className="footer-text">

                    Beats Infinity • Singer Registration

                </div>


            </div>

        </div>

    );

};


export default SingerRegistration;